# Generated by Django 3.1.7 on 2021-02-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0005_auto_20210228_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='existencia',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
